-- Better Auth rate limiting with storage: 'database'.
-- Generated by: bunx --bun @better-auth/cli generate --config src/lib/auth.cli.ts

CREATE TABLE IF NOT EXISTS "rateLimit" (
  "id"          TEXT NOT NULL PRIMARY KEY,
  "key"         TEXT NOT NULL UNIQUE,
  "count"       INTEGER NOT NULL,
  "lastRequest" INTEGER NOT NULL
);
